### ISSUE TITLE
Create Hamburger Menu

### ISSUE THREAD

**Issue by awalls1** [stuartkershaw/codefellows-portfolio#4]
Have menu items hide and display hamburger menu when screen is resized below a certain pixel size.

**Comment by stuartkershaw** [comment]
Decided to take a different path with this. Since I'm really just serving text and links, I want to simply display it all on mobile. So, I remove the nav items and the show/hide on mobile and go with a full length top-to-bottom of my site text instead:

https://github.com/stuartkershaw/codefellows-portfolio/commit/f2b590dd80b6f166726d45062f172c698d05a622
